In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("diminos_data.csv")
data

       order_id      order_placed_at          order_delivered_at
0       1523111  2023-03-01 00:00:59  2023-03-01 00:18:07.443132
1       1523112  2023-03-01 00:03:59  2023-03-01 00:19:34.925241
2       1523113  2023-03-01 00:07:22  2023-03-01 00:22:28.291385
3       1523114  2023-03-01 00:07:47  2023-03-01 00:46:19.019399
4       1523115  2023-03-01 00:09:03  2023-03-01 00:25:13.619056
...         ...                  ...                         ...
14995   1538106  2023-03-27 23:37:05  2023-03-27 23:52:37.409378
14996   1538107  2023-03-27 23:47:38  2023-03-28 00:04:22.672912
14997   1538108  2023-03-27 23:50:16  2023-03-28 00:05:40.676238
14998   1538109  2023-03-27 23:52:44  2023-03-28 00:08:41.810358
14999   1538110  2023-03-27 23:58:20  2023-03-28 00:13:42.499311

[15000 rows x 3 columns]

In [3]:
data.isnull().sum()

order_id              0
order_placed_at       0
order_delivered_at    0
dtype: int64

In [5]:
data.duplicated().sum()

np.int64(0)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            15000 non-null  int64
 1   order_placed_at     15000 non-null  object
 2   order_delivered_at  15000 non-null  object
dtypes: int64(1), object(2)
memory usage: 351.7+ KB

In [8]:
data['order_placed_at'] = pd.to_datetime(data['order_placed_at'])
data['order_delivered_at'] = pd.to_datetime(data['order_delivered_at'])
data['delivery_time_mins'] = (data['order_delivered_at'] - data['order_placed_at']).dt.total_seconds() / 60

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            15000 non-null  int64
 1   order_placed_at     15000 non-null  datetime64[ns]
 2   order_delivered_at  15000 non-null  datetime64[ns]
 3   delivery_time_mins  15000 non-null  float64
dtypes: datetime64[ns](2), float64(1), int64(1)
memory usage: 468.9 KB

In [10]:
data

,order_id,order_placed_at,order_delivered_at,delivery_time_mins
0,1523111,2023-03-01 00:00:59,2023-03-01 00:18:07.443132,17.140719
1,1523112,2023-03-01 00:03:59,2023-03-01 00:19:34.925241,15.598754
2,1523113,2023-03-01 00:07:22,2023-03-01 00:22:28.291385,15.104856
3,1523114,2023-03-01 00:07:47,2023-03-01 00:46:19.019399,38.533657
4,1523115,2023-03-01 00:09:03,2023-03-01 00:25:13.619056,16.176984
...,...,...,...,...
14995,1538106,2023-03-27 23:37:05,2023-03-27 23:52:37.409378,15.540156
14996,1538107,2023-03-27 23:47:38,2023-03-28 00:04:22.672912,16.744549
14997,1538108,2023-03-27 23:50:16,2023-03-28 00:05:40.676238,15.411271
14998,1538109,2023-03-27 23:52:44,2023-03-28 00:08:41.810358,15.963506
14999,1538110,2023-03-27 23:58:20,2023-03-28 00:13:42.499311,15.374989

In [12]:
percentile_95 = data['delivery_time_mins'].quantile(0.95)
percentile_95

np.float64(27.261043996666658)

In [13]:
data['delivery_time_mins'].describe()

count    15000.000000
mean        20.499389
std         96.160362
min         15.000010
25%         15.274826
50%         15.797986
75%         17.279661
max       7299.831375
Name: delivery_time_mins, dtype: float64

In [16]:
late_orders = data[data['delivery_time_mins'] > 31]
late_orders

,order_id,order_placed_at,order_delivered_at,delivery_time_mins
3,1523114,2023-03-01 00:07:47,2023-03-01 00:46:19.019399,38.533657
24,1523135,2023-03-01 01:11:53,2023-03-01 05:07:54.563978,236.026066
47,1523158,2023-03-01 01:57:16,2023-03-01 02:30:19.851911,33.064199
117,1523228,2023-03-01 04:59:04,2023-03-01 18:06:52.046891,787.800782
174,1523285,2023-03-01 07:22:11,2023-03-01 08:12:51.906470,50.681774
...,...,...,...,...
14841,1537952,2023-03-27 16:42:37,2023-03-27 17:43:13.294744,60.604912
14855,1537966,2023-03-27 17:16:14,2023-03-27 17:49:07.476278,32.891271
14899,1538010,2023-03-27 19:31:50,2023-03-27 20:08:26.866824,36.614447
14939,1538050,2023-03-27 21:17:20,2023-03-27 21:54:03.464048,36.724401
14953,1538064,2023-03-27 22:04:53,2023-03-27 22:55:03.230465,50.170508

In [19]:
late_orders['delivery_time_mins'].describe()

count     557.000000
mean      118.586833
std       489.153001
min        31.017259
25%        35.049563
50%        42.810701
75%        68.072933
max      7299.831375
Name: delivery_time_mins, dtype: float64

In [17]:
late_percentage = len(late_orders) / len(data) * 100
late_percentage

3.713333333333333

Conclusion:

Performance Metric: The 95th percentile delivery time is 27.26 minutes, which is safely below Diminos’ 31‑minute requirement.
Overall Delivery Speed: Most orders are delivered in 15–20 minutes, showing strong operational efficiency.
Late Deliveries: About 557 orders (3.7%) exceeded 31 minutes. While this doesn’t affect the 95th percentile yet, it highlights potential risks.
Outliers: Extreme cases (200+ minutes, even 7000+ minutes) are likely system errors or failed deliveries. These inflate variability and should be investigated.

Kanav is worried that he might lose the franchise if he is not able to meet the metric and wants your help in order to understand his store's performance so that he can take some actions to prevent his business. 
---- Kanav successfully meet the metric.
---- If not,precautions like
Investigate Outliers: Orders >120 minutes should be reviewed—likely system errors or failed deliveries.
Increase Staff: Add more staff at peek time to reduce delays.
Set Internal SLA: Aim for 90th percentile <25 minutes to build a buffer.
Weekly Monitoring: Track late orders and percentile trends with a dashboard.
Customer Communication: Proactively inform customers during busy hours to manage expectations.